import 'package:flutter/material.dart';

const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFB8A9F0),
  onPrimary: Color(0xFF1A1525),
  primaryContainer: Color(0xFF4A3D8F),
  onPrimaryContainer: Color(0xFFF0ECFF),
  secondary: Color(0xFF4FC3B8),
  onSecondary: Color(0xFF0D2927),
  secondaryContainer: Color(0xFF1B6B65),
  onSecondaryContainer: Color(0xFFE0F5F3),
  tertiary: Color(0xFFFFD580),
  onTertiary: Color(0xFF3D2E00),
  tertiaryContainer: Color(0xFF5C4500),
  onTertiaryContainer: Color(0xFFFFF3D6),
  error: Color(0xFFCF6679),
  onError: Color(0xFF140C0D),
  errorContainer: Color(0xFFB1384E),
  onErrorContainer: Color(0xFFFBE8EC),
  surface: Color(0xFF1A1525),
  onSurface: Color(0xFFE6E1E5),
  surfaceContainerHighest: Color(0xFF2C2730),
  onSurfaceVariant: Color(0xFFCAC4D0),
  outline: Color(0xFF938F99),
  outlineVariant: Color(0xFF49454F),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFFE6E1E5),
  onInverseSurface: Color(0xFF313033),
  inversePrimary: Color(0xFF5B4BA8),
  surfaceTint: Color(0xFFB8A9F0),
);

ThemeData dark = ThemeData(
  useMaterial3: true,
  fontFamily: 'System',
  scaffoldBackgroundColor: const Color(0xFF1A1525),
  primaryColor: const Color(0xFFB8A9F0),
  brightness: Brightness.dark,
  cardColor: const Color(0xFF242030),
  hintColor: const Color(0xFFCAC4D0),
  focusColor: const Color(0xFFADC4C8),
  shadowColor: Colors.black.withValues(alpha: 0.4),
  pageTransitionsTheme: const PageTransitionsTheme(
    builders: {
      TargetPlatform.android: ZoomPageTransitionsBuilder(),
      TargetPlatform.iOS: ZoomPageTransitionsBuilder(),
      TargetPlatform.fuchsia: ZoomPageTransitionsBuilder(),
    },
  ),
  colorScheme: darkColorScheme,
  textTheme: const TextTheme(
    displayLarge: TextStyle(fontWeight: FontWeight.w500, fontSize: 57),
    displayMedium: TextStyle(fontWeight: FontWeight.w500, fontSize: 45),
    displaySmall: TextStyle(fontWeight: FontWeight.w500, fontSize: 36),
    headlineLarge: TextStyle(fontWeight: FontWeight.w500, fontSize: 32),
    headlineMedium: TextStyle(fontWeight: FontWeight.w500, fontSize: 28),
    headlineSmall: TextStyle(fontWeight: FontWeight.w500, fontSize: 24),
    titleLarge: TextStyle(fontWeight: FontWeight.w500, fontSize: 20),
    titleMedium: TextStyle(fontSize: 16.0, fontWeight: FontWeight.w500),
    titleSmall: TextStyle(fontSize: 14.0, fontWeight: FontWeight.w500),
    bodyLarge: TextStyle(fontSize: 16.0, fontWeight: FontWeight.w400),
    bodyMedium: TextStyle(fontSize: 14.0, fontWeight: FontWeight.w400),
    bodySmall: TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400),
    labelLarge: TextStyle(fontSize: 14.0, fontWeight: FontWeight.w500),
    labelMedium: TextStyle(fontSize: 12.0, fontWeight: FontWeight.w500),
    labelSmall: TextStyle(fontSize: 11.0, fontWeight: FontWeight.w500),
  ),
);
