import 'package:flutter/material.dart';
import 'package:mind_insight/src/core/constant/app_dimensions.dart';

const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF7C6FCB),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFF0ECFF),
  onPrimaryContainer: Color(0xFF211D33),
  secondary: Color(0xFF2F9C95),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE0F5F3),
  onSecondaryContainer: Color(0xFF0D2927),
  tertiary: Color(0xFFFFC65A),
  onTertiary: Color(0xFF211D33),
  tertiaryContainer: Color(0xFFFFF3D6),
  onTertiaryContainer: Color(0xFF3D2E00),
  error: Color(0xFFB00020),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFCD8DF),
  onErrorContainer: Color(0xFF410002),
  surface: Color(0xFFFFFBF4),
  onSurface: Color(0xFF211D33),
  surfaceContainerHighest: Color(0xFFECE7DF),
  onSurfaceVariant: Color(0xFF7A748C),
  outline: Color(0xFF7A748C),
  outlineVariant: Color(0xFFECE7DF),
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: Color(0xFF211D33),
  onInverseSurface: Color(0xFFF5F5F5),
  inversePrimary: Color(0xFFB8A9F0),
  surfaceTint: Color(0xFFFFFBF4),
);

ThemeData light = ThemeData(
  useMaterial3: true,
  fontFamily: 'System',
  scaffoldBackgroundColor: const Color(0xFFFFFBF4),
  brightness: Brightness.light,
  cardColor: Colors.white,
  focusColor: const Color(0xFFADC4C8),
  hintColor: const Color(0xFF7A748C),
  shadowColor: const Color.fromARGB(0, 224, 224, 224),
  pageTransitionsTheme: const PageTransitionsTheme(
    builders: {
      TargetPlatform.android: ZoomPageTransitionsBuilder(),
      TargetPlatform.iOS: ZoomPageTransitionsBuilder(),
      TargetPlatform.fuchsia: ZoomPageTransitionsBuilder(),
    },
  ),
  colorScheme: lightColorScheme,
  textTheme: const TextTheme(
    displayLarge: TextStyle(fontWeight: FontWeight.w500, fontSize: 57),
    displayMedium: TextStyle(fontWeight: FontWeight.w500, fontSize: 45),
    displaySmall: TextStyle(fontWeight: FontWeight.w500, fontSize: 36),
    headlineLarge: TextStyle(fontWeight: FontWeight.w500, fontSize: 32),
    headlineMedium: TextStyle(fontWeight: FontWeight.w500, fontSize: 28),
    headlineSmall: TextStyle(fontWeight: FontWeight.w500, fontSize: 24),
    titleLarge: TextStyle(fontWeight: FontWeight.w500, fontSize: 20),
    titleMedium: TextStyle(fontSize: 16.0, fontWeight: FontWeight.w500),
    titleSmall: TextStyle(fontSize: Dimensions.fontSizeDefault, fontWeight: FontWeight.w500),
    bodyLarge: TextStyle(fontSize: 16.0, fontWeight: FontWeight.w400),
    bodyMedium: TextStyle(fontSize: Dimensions.fontSizeDefault, fontWeight: FontWeight.w400),
    bodySmall: TextStyle(fontSize: 12.0, fontWeight: FontWeight.w400),
    labelLarge: TextStyle(fontSize: Dimensions.fontSizeDefault, fontWeight: FontWeight.w500),
    labelMedium: TextStyle(fontSize: 12.0, fontWeight: FontWeight.w500),
    labelSmall: TextStyle(fontSize: 11.0, fontWeight: FontWeight.w500),
  ),
);
